### ISSUE TITLE
Sample code not working

### ISSUE THREAD

**Issue by jamint** [protyze/aframe-alongpath-component#9]
Could very well be me, but the demo code doesn't appear to work.

index.js:86 A-Frame Version: 0.5.0 (Date 26-04-2017, Commit #8abc9d5)
index.js:87 three Version: ^0.84.0
index.js:88 WebVR Polyfill Version: dmarcos/webvr-polyfill#a02a8089b
three.js:19802 THREE.WebGLRenderer 84
aframe-alongpath-component.min.js:1 Uncaught TypeError: Cannot read property 'curve' of undefined
    at i.tick (https://rawgit.com/protyze/aframe-alongpath-component/master/dist/aframe-alongpath-component.min.js:1:1099)
    at https://rawgit.com/aframevr/aframe/master/dist/aframe-master.min.js:251:6283
    at Array.forEach (native)
    at HTMLElement.value (https://rawgit.com/aframevr/aframe/master/dist/aframe-master.min.js:251:6245)
    at HTMLElement.value (https://rawgit.com/aframevr/aframe/master/dist/aframe-master.min.js:251:6489)
    at HTMLElement.render (https://rawgit.com/aframevr/aframe/master/dist/aframe-master.min.js:372:132)
    at e (https://rawgit.com/aframevr/aframe/master/dist/aframe-master.min.js:251:5621)
    at HTMLElement.<anonymous> (https://rawgit.com/aframevr/aframe/master/dist/aframe-master.min.js:251:5797)
    at Object.module.exports.fireEvent (https://rawgit.com/aframevr/aframe/master/dist/aframe-master.min.js:390:2122)
    at https://rawgit.com/aframevr/aframe/master/dist/aframe-master.min.js:241:2791
tick @ aframe-alongpath-component.min.js:1
(anonymous) @ a-scene.js:450
value @ a-scene.js:448
value @ a-scene.js:472
(anonymous) @ bind.js:12
e @ a-scene.js:392
(anonymous) @ a-scene.js:379
module.exports.fireEvent @ index.js:96
(anonymous) @ a-node.js:233
value @ a-node.js:232
setActiveCamera @ camera.js:107
update @ camera.js:70
updateProperties @ component.js:220
value @ a-entity.js:525
e @ a-entity.js:501
value @ a-entity.js:483
(anonymous) @ a-entity.js:307
(anonymous) @ a-node.js:117
aframe-alongpath-component.min.js:1 Uncaught TypeError: Cannot read property 'curve' of undefined
    at i.tick (https://rawgit.com/protyze/aframe-alongpath-component/master/dist/aframe-alongpath-component.min.js:1:1099)
    at https://rawgit.com/aframevr/aframe/master/dist/aframe-master.min.js:251:6283
    at Array.forEach (native)
    at HTMLElement.value (https://rawgit.com/aframevr/aframe/master/dist/aframe-master.min.js:251:6245)
    at HTMLElement.value (https://rawgit.com/aframevr/aframe/master/dist/aframe-master.min.js:251:6489)
    at HTMLElement.render (https://rawgit.com/aframevr/aframe/master/dist/aframe-master.min.js:372:132)
    at e (https://rawgit.com/aframevr/aframe/master/dist/aframe-master.min.js:251:5621)
    at HTMLElement.<anonymous> (https://rawgit.com/aframevr/aframe/master/dist/aframe-master.min.js:251:5797)
    at Object.module.exports.fireEvent (https://rawgit.com/aframevr/aframe/master/dist/aframe-master.min.js:390:2122)
    at https://rawgit.com/aframevr/aframe/master/dist/aframe-master.min.js:241:2791

**Comment by protyze** [comment]
Should be fixed now: https://protyze.github.io/aframe-alongpath-component/
